// AUTO-GENERATED by scripts/extract-props.ts — do not edit manually
// Generated: 2026-03-13T02:24:49.749Z

export interface RegistryProp {
  name: string;
  type: string;
  required: boolean;
  defaultValue?: string;
  description?: string;
}

export const generatedProps: Record<string, RegistryProp[]> = {
  "accordion": [
    { name: "dividerColor", type: "string", required: false },
    { name: "dividerWeight", type: "number", required: false, defaultValue: "1" },
    { name: "dividerEnabled", type: "boolean", required: false, defaultValue: "true" },
    { name: "paddingH", type: "number", required: false },
    { name: "paddingW", type: "number", required: false },
    { name: "spacing", type: "number", required: false, defaultValue: "0" },
  ],
  "alert": [
    { name: "dismissible", type: "boolean", required: false, defaultValue: "false" },
    { name: "showIcon", type: "boolean", required: false, defaultValue: "true" },
    { name: "icon", type: "React.ReactNode", required: false },
    { name: "onDismiss", type: "() => void", required: false },
    { name: "variant", type: "\"default\" | \"info\" | \"success\" | \"warning\" | \"error\"", required: false, defaultValue: "\\\"info\\\"" },
  ],
  "animated-text": [
    { name: "text", type: "string", required: true },
    { name: "variant", type: "AnimatedTextVariant", required: false, defaultValue: "'blur-in'" },
    { name: "speed", type: "number", required: false },
    { name: "stagger", type: "number", required: false },
    { name: "splitBy", type: "AnimatedTextSplitBy", required: false, defaultValue: "'word'" },
    { name: "gradientColor1", type: "string", required: false },
    { name: "gradientColor2", type: "string", required: false },
    { name: "trigger", type: "AnimatedTextTrigger", required: false, defaultValue: "'mount'" },
    { name: "className", type: "string", required: false },
    { name: "style", type: "React.CSSProperties", required: false },
  ],
  "avatar": [
    { name: "shape", type: "\"circle\" | \"rounded\"", required: false, defaultValue: "\"circle\"" },
    { name: "size", type: "\"sm\" | \"md\" | \"lg\"", required: false, defaultValue: "\"md\"" },
    { name: "badge", type: "boolean", required: false, defaultValue: "false" },
    { name: "badgeColor", type: "string", required: false, defaultValue: "\"bg-green-500\"" },
    { name: "customSize", type: "number", required: false },
    { name: "radius", type: "number", required: false },
    { name: "bgColor", type: "string", required: false },
    { name: "bgGradientTo", type: "string", required: false },
    { name: "bgMode", type: "\"solid\" | \"gradient\"", required: false, defaultValue: "\"solid\"" },
    { name: "bgOpacity", type: "number", required: false },
    { name: "strokeWeight", type: "number", required: false },
    { name: "strokeColor", type: "string", required: false },
    { name: "strokeOpacity", type: "number", required: false },
  ],
  "badge": [
    { name: "variant", type: "\"default\" | \"secondary\" | \"destructive\" | \"outline\" | \"ghost\" | \"link\"", required: false, defaultValue: "\\\"default\\\"" },
    { name: "asChild", type: "boolean", required: false, defaultValue: "false" },
  ],
  "button": [
    { name: "variant", type: "\"default\" | \"destructive\" | \"outline\" | \"secondary\" | \"ghost\" | \"link\"", required: false, defaultValue: "\\\"default\\\"" },
    { name: "size", type: "\"default\" | \"xs\" | \"sm\" | \"lg\" | \"icon\" | \"icon-xs\" | \"icon-sm\" | \"icon-lg\"", required: false, defaultValue: "\\\"default\\\"" },
    { name: "asChild", type: "boolean", required: false, defaultValue: "false" },
  ],
  "card": [
    { name: "showDividers", type: "boolean", required: false },
    { name: "variant", type: "\"default\" | \"bordered\" | \"elevated\" | \"glass\"", required: false, defaultValue: "default" },
  ],
  "checkbox": [],
  "data-table": [
    { name: "columns", type: "DataTableColumn[]", required: true },
    { name: "data", type: "Record<string, string>[]", required: true },
    { name: "sortable", type: "boolean", required: false, defaultValue: "false" },
    { name: "striped", type: "boolean", required: false, defaultValue: "false" },
    { name: "size", type: "\"sm\" | \"md\" | \"lg\"", required: false, defaultValue: "\"md\"" },
    { name: "headerBg", type: "string", required: false },
    { name: "rowBg", type: "string", required: false },
    { name: "stripedBg", type: "string", required: false },
    { name: "textColor", type: "string", required: false },
    { name: "headerTextColor", type: "string", required: false },
    { name: "borderColor", type: "string", required: false },
    { name: "badgeColors", type: "Record<string, { bg: string; text: string }>", required: false },
    { name: "onSort", type: "(columnKey: string, direction: SortDirection) => void", required: false },
    { name: "variant", type: "\"default\" | \"bordered\"", required: false, defaultValue: "default" },
    { name: "size", type: "\"sm\" | \"md\" | \"lg\"", required: false, defaultValue: "\\\"md\\\"" },
    { name: "key", type: "string", required: true },
    { name: "label", type: "string", required: true },
    { name: "sortable", type: "boolean", required: false },
    { name: "align", type: "\"left\" | \"center\" | \"right\"", required: false },
    { name: "variant", type: "\"text\" | \"badge\"", required: false },
  ],
  "dialog": [
    { name: "title", type: "string", required: false },
    { name: "description", type: "string", required: false },
  ],
  "drawer": [
    { name: "side", type: "\"right\" | \"left\" | \"top\" | \"bottom\"", required: false, defaultValue: "\\\"right\\\"" },
  ],
  "dropdown-menu": [],
  "input": [],
  "navigation-menu": [
    { name: "orientation", type: "\"horizontal\" | \"vertical\"", required: false, defaultValue: "\\\"horizontal\\\"" },
    { name: "hoverBg", type: "string", required: false },
    { name: "hoverText", type: "string", required: false },
    { name: "activeBg", type: "string", required: false },
    { name: "activeText", type: "string", required: false },
  ],
  "popover": [],
  "progress": [
    { name: "showLabel", type: "boolean", required: false, defaultValue: "false" },
    { name: "animateValue", type: "boolean", required: false, defaultValue: "true" },
    { name: "indicatorClassName", type: "string", required: false },
    { name: "trackColor", type: "string", required: false },
    { name: "indicatorColor", type: "string", required: false },
    { name: "labelColor", type: "string", required: false },
    { name: "circularSize", type: "number", required: false },
    { name: "circularStrokeWidth", type: "number", required: false },
    { name: "variant", type: "\"linear\" | \"circular\"", required: false, defaultValue: "\\\"linear\\\"" },
    { name: "size", type: "\"sm\" | \"md\" | \"lg\"", required: false, defaultValue: "\\\"md\\\"" },
  ],
  "slider": [],
  "switch": [
    { name: "size", type: "\"sm\" | \"default\"", required: false, defaultValue: "\"default\"" },
    { name: "trackColor", type: "string", required: false },
    { name: "trackActiveColor", type: "string", required: false },
    { name: "thumbColor", type: "string", required: false },
    { name: "thumbActiveColor", type: "string", required: false },
    { name: "thumbContent", type: "React.ReactNode", required: false },
  ],
  "tabs": [
    { name: "variant", type: "\"default\" | \"line\" | \"pill\" | \"segment\"", required: false, defaultValue: "\\\"default\\\"" },
    { name: "listBg", type: "string", required: false },
    { name: "fullWidth", type: "boolean", required: false, defaultValue: "false" },
  ],
  "tooltip": [
    { name: "arrow", type: "boolean", required: false, defaultValue: "true" },
    { name: "children", type: "React.ReactNode", required: false },
  ],
  "stateful-button": [
    { name: "className", type: "string", required: false },
    { name: "children", type: "React.ReactNode", required: true },
    { name: "state", type: "StatefulButtonState", required: false },
    { name: "resultState", type: "StatefulButtonResultState", required: false, defaultValue: "'success'" },
    { name: "resetDelayMs", type: "number", required: false, defaultValue: "1600" },
    { name: "loadingDurationMs", type: "number", required: false, defaultValue: "600" },
    { name: "loadingPosition", type: "'left' | 'right'", required: false, defaultValue: "'left'" },
    { name: "autoPlay", type: "boolean", required: false, defaultValue: "false" },
    { name: "autoPlayKey", type: "string | number", required: false },
  ],
};
